/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TraversalLazyImport = createFileRoute('/traversal')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TraversalLazyRoute = TraversalLazyImport.update({
  path: '/traversal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/traversal.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/traversal': {
      id: '/traversal'
      path: '/traversal'
      fullPath: '/traversal'
      preLoaderRoute: typeof TraversalLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/traversal': typeof TraversalLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/traversal': typeof TraversalLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/traversal': typeof TraversalLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/traversal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/traversal'
  id: '__root__' | '/' | '/traversal'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TraversalLazyRoute: typeof TraversalLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TraversalLazyRoute: TraversalLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/traversal"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/traversal": {
      "filePath": "traversal.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
